/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Desenvolvimento
 */
public class JFCadastro extends javax.swing.JInternalFrame {
   
   /**
    * Creates new form JFCadastro
    */
   public JFCadastro() {
      initComponents();
      
          String txt = "D:\\JavaFX\\JavaApplication3\\estados.txt";
         try{
         BufferedReader ler = new BufferedReader(new FileReader(txt));
         String linha = ler.readLine();
         int cont = 0;
         while(linha != null){
               optionUF.addItem(linha);
           
               cont++;
               
               ler.readLine();
            }
            else
            {
               break;
            }
            }
         ler.close();
         }catch(IOException e){
            System.err.println("Error");
         }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jTextField2 = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      txtCodigo = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      txtNome = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      txtCPF = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      txtCidade = new javax.swing.JTextField();
      buttonRegister = new javax.swing.JButton();
      optionUF = new javax.swing.JComboBox<>();

      jTextField2.setToolTipText("");
      jTextField2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField2ActionPerformed(evt);
         }
      });

      setBackground(new java.awt.Color(204, 204, 255));
      setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
      setClosable(true);
      setIconifiable(true);
      setMaximizable(true);
      setResizable(true);
      setTitle("Cadastro de Cliente");
      setToolTipText("");

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      jLabel1.setText("Nome");

      txtCodigo.setToolTipText("");
      txtCodigo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtCodigoActionPerformed(evt);
         }
      });

      jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      jLabel2.setText("Código");

      txtNome.setToolTipText("");
      txtNome.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtNomeActionPerformed(evt);
         }
      });

      jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      jLabel4.setText("UF");

      jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      jLabel5.setText("CPF");

      txtCPF.setToolTipText("");
      txtCPF.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtCPFActionPerformed(evt);
         }
      });

      jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      jLabel6.setText("Cidade");

      txtCidade.setToolTipText("");
      txtCidade.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtCidadeActionPerformed(evt);
         }
      });

      buttonRegister.setText("Registrar");
      buttonRegister.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonRegisterActionPerformed(evt);
         }
      });

      optionUF.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
         public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
         }
         public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
         }
         public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            optionUFPopupMenuWillBecomeVisible(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel6)
                  .addGap(18, 18, 18)
                  .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(buttonRegister)
                  .addGroup(layout.createSequentialGroup()
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                     .addGap(16, 16, 16)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(optionUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addContainerGap(150, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel1))
            .addGap(5, 5, 5)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel6)
               .addComponent(txtCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel4)
               .addComponent(optionUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(28, 28, 28)
            .addComponent(buttonRegister)
            .addContainerGap(96, Short.MAX_VALUE))
      );

      txtCodigo.getAccessibleContext().setAccessibleName("");
      optionUF.getAccessibleContext().setAccessibleName("");

      getAccessibleContext().setAccessibleName("");

      setBounds(100, 15, 380, 319);
   }// </editor-fold>//GEN-END:initComponents

   private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtCodigoActionPerformed

   private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField2ActionPerformed

   private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtNomeActionPerformed

   private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtCPFActionPerformed

   private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtCidadeActionPerformed



   private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
      // TODO add your handling code here:

      JIFPrivate Cliente = new JIFPrivate();
      if(!"".equals(txtCodigo.getText())){
         Cliente.setCodigo(Integer.parseInt(txtCodigo.getText()));
      }else{
         txtCodigo.requestFocus();
      }
      if(!"".equals(txtNome.getText())){
               Cliente.setNome(txtNome.getText());

      } else {
                  txtNome.requestFocus();

      }
      if(!"".equals(txtCPF.getText())){
               Cliente.setCPF(txtCPF.getText());
      } else{
                  txtCPF.requestFocus();

      }
      if (!"".equals(txtCidade.getText())){
               Cliente.setCidade(txtCidade.getText());
      } else {
               txtCidade.requestFocus();
      }
      if (!"".equals(optionUF.getSelectedItem().toString())){
        Cliente.setUF(optionUF.getSelectedItem().toString());
      } else{
                  optionUF.requestFocus();
      }
            System.out.println("" + Cliente);
      JOptionPane.showMessageDialog(rootPane, "Conta criada", "Suceso!", 1);
      dispose();


   }//GEN-LAST:event_buttonRegisterActionPerformed

   private void optionUFPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_optionUFPopupMenuWillBecomeVisible
      // TODO add your handling code here:

   }//GEN-LAST:event_optionUFPopupMenuWillBecomeVisible


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton buttonRegister;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JTextField jTextField2;
   private javax.swing.JComboBox<String> optionUF;
   private javax.swing.JTextField txtCPF;
   private javax.swing.JTextField txtCidade;
   private javax.swing.JTextField txtCodigo;
   private javax.swing.JTextField txtNome;
   // End of variables declaration//GEN-END:variables
}
