/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;


import com.sun.glass.events.KeyEvent;
import static com.sun.javafx.util.Utils.contains;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Desenvolvimento
 */
public class PainelLogin extends javax.swing.JFrame {

   /**
    * Creates new form PainelLogin
    */
   public PainelLogin() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jMenu1 = new javax.swing.JMenu();
      jMenu2 = new javax.swing.JMenu();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      Sair = new javax.swing.JButton();
      buttonLogar = new javax.swing.JToggleButton();
      username = new javax.swing.JTextField();
      password = new javax.swing.JPasswordField();
      barrinha = new javax.swing.JProgressBar();
      Mesg = new javax.swing.JLabel();

      jMenu1.setText("jMenu1");

      jMenu2.setText("jMenu2");

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Painel de Login");
      setBackground(new java.awt.Color(153, 153, 255));
      setForeground(java.awt.Color.blue);
      setLocation(new java.awt.Point(550, 300));

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      jLabel1.setText("Usuário");

      jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
      jLabel2.setText("Senha");

      Sair.setText("Sair");
      Sair.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      Sair.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            SairActionPerformed(evt);
         }
      });

      buttonLogar.setText("Logar");
      buttonLogar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      buttonLogar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonLogarActionPerformed(evt);
         }
      });
      buttonLogar.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            buttonLogarKeyPressed(evt);
         }
      });

      username.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            usernameKeyPressed(evt);
         }
      });

      password.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            passwordKeyPressed(evt);
         }
      });

      barrinha.setForeground(new java.awt.Color(0, 0, 0));
      barrinha.setBorderPainted(false);
      barrinha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      barrinha.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
      barrinha.setName(""); // NOI18N
      barrinha.setStringPainted(true);

      Mesg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      Mesg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(barrinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(25, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1)
               .addComponent(jLabel2))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(25, Short.MAX_VALUE))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
               .addComponent(Mesg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(buttonLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(18, 18, 18)
                  .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(43, 43, 43))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(20, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(buttonLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Mesg, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(barrinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      jLabel1.getAccessibleContext().setAccessibleName("username");
      jLabel2.getAccessibleContext().setAccessibleName("password");

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   public void login(){
      String p1 = username.getText();

      if ("isaac.oliveira".equals(p1)){
         String s = password.getText();
         if ("admin123".equals(s)){

           new Thread() {
            public void run(){
               for (int i=0; i <=100; i++){
                  if (i <= 25){
                  Mesg.setText("Preparando o sistema...");
                  }else if (i<=50){
                     Mesg.setText("Configurando o sistema ...");
                  } else if (i<=75 ){
                     Mesg.setText("Carregando ajustes finais...");
                  }else if(i<=95){
                     Mesg.setText("Abrindo o sistema...");
                  }
                  try{

                     sleep(10);
                     barrinha.setValue(i);

                  }catch(Exception msg){
                     System.err.println("Erro de execução" + msg);
                  }
               }

               Menu Console = new Menu();
                     Console.setVisible(true);
                     dispose();
                     JOptionPane.showMessageDialog(rootPane, "Bem-vindo ao sistema "+username.getText());
            }
         }.start();
         }
         else if(!"admin123".equals(s)){
            password.setText("");
            password.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Password: Oops something is wrong!" , "Error", 3);
         }
      } else if (!"isaac.oliveira".equals(p1)) {
                  username.setText("");
                  password.setText("");
                  username.requestFocus();
                     JOptionPane.showMessageDialog(rootPane, "Username: Are you correct with this information?", "Error", 3);

      }
   }

   private void buttonLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogarActionPerformed
      // TODO add your handling code here:
      //Verificação de senha e usuário!
      login();
   }//GEN-LAST:event_buttonLogarActionPerformed

   private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
      // TODO add your handling code here:
      String palavra = "IFPR 123 ";
      String senha = "";
      String usuario = "";
      int tam = palavra.length();
      //
      //senha = palavra.substring(5, 8);
      //System.out.println("Usuário: "+ usuario+ "\nSenha: "+senha);]
      String[] a = palavra.split(" ");
      System.out.println(Arrays.toString(palavra.split(" ")));
      usuario = a[0];
      senha = a[1];
      System.out.println(usuario);
      System.out.println(senha);

   }//GEN-LAST:event_SairActionPerformed

   private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
      // TODO add your handling code here:
      if (evt.getKeyCode() == KeyEvent.VK_ENTER){
         password.requestFocus();
      }
   }//GEN-LAST:event_usernameKeyPressed

   private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
      // TODO add your handling code here:
      if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         buttonLogar.requestFocus();
      }
   }//GEN-LAST:event_passwordKeyPressed

   private void buttonLogarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonLogarKeyPressed
     // TODO add your handling code here:
     if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        login();
     }
   }//GEN-LAST:event_buttonLogarKeyPressed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {

      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      }
      catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(PainelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(PainelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(PainelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(PainelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new PainelLogin().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel Mesg;
   private javax.swing.JButton Sair;
   private javax.swing.JProgressBar barrinha;
   private javax.swing.JToggleButton buttonLogar;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JPasswordField password;
   private javax.swing.JTextField username;
   // End of variables declaration//GEN-END:variables

   private void contains(String _) {
      throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   }
}
